[package]
name = "claude-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] } 
anthropic-ai-sdk = "0.1.3"
colored = "3.0.0"
futures-util = "0.3.31"

